routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'main', 'middleware'=>'auth'], function () {
	Route::resource('/warehouse', 'WarehouseController');
	Route::resource('/inventory', 'InventoryController');
	Route::resource('/customer', 'CustomerController');
	Route::resource('/transportation', 'TransportationController');
	Route::resource('/sales-order', 'SalesOrderController');
	Route::resource('/logistic', 'DistanceController');
	Route::resource('/routing', 'RoutingController');
	Route::resource('/store', 'StoreController');

	Route::get('/manager', 'ManagerController@index')->name('manager.index');

	Route::get('/user/profile', 'UserController@showProfile')->name('profile.show');
	Route::put('/user/profile', 'UserController@updateProfile')->name('profile.update');

	Route::get('/place/city/{province_id}', 'PlaceController@getCity')->name('city.list');
	Route::get('/place/district/{city_id}', 'PlaceController@getDistrict')->name('district.list');
});

app/Inventory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    public function warehouse()
    {
    	return $this->belongsTo('App\Warehouse');
    }
}

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use App\Inventory;
use Session;

class InventoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $inventories = Inventory::with('warehouse');
            $inventories = $inventories->select('*');
            
            return Datatables::of($inventories)
                ->addIndexColumn()
                ->addColumn('action', function($inventory){
                    return view('partials._action', [
                        'model'           => $inventory,
                        'form_url'        => route('inventory.destroy', $inventory->id),
                        'edit_url'        => route('inventory.edit', $inventory->id)
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('inventories.index'); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('inventories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
          'warehouse_id' => 'required|numeric',
          'quantity' => 'required|numeric',
        ]);

        $check = Inventory::where('warehouse_id', $request->warehouse_id)->first();
        
        if ($check) {
            Session::flash("flash_notification", [
              "level"=>"warning",
              "message"=>"Data inentory untuk warehouse ".$check->warehouse->name." sudah tersedia!"
            ]);
            
            return redirect()->back();
        }

        $inventory = new Inventory;
        $inventory->warehouse_id = $request->warehouse_id;
        $inventory->quantity = $request->quantity;
        $inventory->save();

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Data berhasil di simpan"
        ]);
        
        return redirect()->route('inventory.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $inventory = Inventory::find($id);
        return view('inventories.edit')->with(compact('inventory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
          'warehouse_id' => 'required|numeric',
          'quantity' => 'required|numeric',
        ]);

        $inventory = Inventory::find($id);
        $inventory->warehouse_id = $request->warehouse_id;
        $inventory->quantity = $request->quantity;
        $inventory->save();

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Data berhasil di ubah"
        ]);
        
        return redirect()->route('inventory.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $inventory = Inventory::destroy($id);

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menghapus data"
        ]);

        return redirect()->route('inventory.index');
    }
}

resources/views/inventories/create.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Inventory</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Tambah Inventory</h6>
        </div>
        <div class="card-body">
          
          <form method="POST" action="{{ route('inventory.store') }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="form-group {{ $errors->has('warehouse_id') ? ' has-error' : '' }}">
              <label for="warehouse_id">Warehouse</label>
              <select id="warehouse_id" class="form-control @if ($errors->has('warehouse_id')) is-invalid @endif" name="warehouse_id" tabindex="1">
                <option value=""></option>
                @foreach (\App\Warehouse::all() as $item)
                  <option value="{{ $item->id }}">{{ $item->name }}</option>
                @endforeach
              </select>
              @if ($errors->has('warehouse_id'))
                <div class="invalid-feedback">
                  {{ $errors->first('warehouse_id') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('quantity') ? ' has-error' : '' }}">
              <label for="quantity">Jumlah</label>
              <input id="quantity" type="number" class="form-control @if ($errors->has('quantity')) is-invalid @endif" name="quantity" tabindex="1" value="{{ old('quantity') }}">
              @if ($errors->has('quantity'))
                <div class="invalid-feedback">
                  {{ $errors->first('quantity') }}
                </div>
              @endif
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" tabindex="1">
                Simpan
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
  <script type="text/javascript">
    $(document).ready(function() {
      $('#warehouse_id').select2({
        placeholder: "Pilih Warehouse"
      });
    });
  </script>
@endsection

resources/views/inventories/edit.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Inventory</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Ubah Inventory</h6>
        </div>
        <div class="card-body">
          
          <form method="POST" action="{{ route('inventory.update', $inventory->id) }}" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PUT') }}

            <div class="form-group {{ $errors->has('warehouse_id') ? ' has-error' : '' }}">
              <label for="warehouse_id">Warehouse</label>
              <select id="warehouse_id" class="form-control @if ($errors->has('warehouse_id')) is-invalid @endif" name="warehouse_id" tabindex="1">
                <option value=""></option>
                @foreach (\App\Warehouse::all() as $item)
                  <option value="{{ $item->id }}" @if ($inventory->warehouse_id == $item->id) selected @endif>{{ $item->name }}</option>
                @endforeach
              </select>
              @if ($errors->has('warehouse_id'))
                <div class="invalid-feedback">
                  {{ $errors->first('warehouse_id') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('quantity') ? ' has-error' : '' }}">
              <label for="quantity">Jumlah</label>
              <input id="quantity" type="number" class="form-control @if ($errors->has('quantity')) is-invalid @endif" name="quantity" tabindex="1" value="{{ $inventory->quantity }}">
              @if ($errors->has('quantity'))
                <div class="invalid-feedback">
                  {{ $errors->first('quantity') }}
                </div>
              @endif
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" tabindex="1">
                Simpan
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
  <script type="text/javascript">
    $(document).ready(function() {
      $('#warehouse_id').select2({
        placeholder: "Pilih Warehouse"
      });
    });
  </script>
@endsection

resources/views/inventories/index.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-start mb-4">
    <h1 class="h3 mb-0 text-gray-800">Inventory</h1>
    <a class="btn btn-sm btn-primary mr-auto ml-4" href="{{ route('inventory.create') }}"><i class="fa fa-plus"></i> Tambah Data</a> 
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">List Inventory</h6>
        </div>
        <div class="card-body">

        <div class="table-responsive">
          <table class="table table-hover table-bordered datatable">
            <thead>                                 
              <tr>
                <th>#</th>
                <th>Warehouse</th>
                <th>Jumlah Inventory</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>

        </div>
      </div>
    </div>
  </div>
@endsection
@section('script')
<script>
  $(document).ready(function() {
      $('.datatable').DataTable({
          processing: true,
          serverSide: true,
          autoWidth: false,
          language: {
              url: '{{ asset('vendor/sb-temp/vendor/datatables/lang/Indonesian.json') }}'
          },
          ajax: {
            url: '{{ route('inventory.index') }}'
          },
          columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'warehouse.name', name: 'warehouse.name'},
            {data: 'quantity', name: 'quantity'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      $(document).on('click','.js-submit-confirm', function(e){
          e.preventDefault();
          swal({
            title: 'Apakah anda yakin ingin menghapus?',
            text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              $(this).closest('form').submit();
            } 
          });
      });
  });
</script>
@endsection