routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'main', 'middleware'=>'auth'], function () {
	Route::resource('/warehouse', 'WarehouseController');
	Route::resource('/inventory', 'InventoryController');
	Route::resource('/customer', 'CustomerController');
	Route::resource('/transportation', 'TransportationController');
	Route::resource('/sales-order', 'SalesOrderController');
	Route::resource('/logistic', 'DistanceController');
	Route::resource('/routing', 'RoutingController');
	Route::resource('/store', 'StoreController');

	Route::get('/manager', 'ManagerController@index')->name('manager.index');

	Route::get('/user/profile', 'UserController@showProfile')->name('profile.show');
	Route::put('/user/profile', 'UserController@updateProfile')->name('profile.update');

	Route::get('/place/city/{province_id}', 'PlaceController@getCity')->name('city.list');
	Route::get('/place/district/{city_id}', 'PlaceController@getDistrict')->name('district.list');
});

app/SalesOrder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SalesOrder extends Model
{
	protected $appends = ['display_status'];

    public function getDisplayStatusAttribute()
    {   
    	$value = $this->status;
        if ($value == 100) {
            $status = "Available";
        } else if ($value == 200) {
            $status = "Finished";
        } else if ($value == 10) {
            $status = "Not Available";
        } else {
            $status = "Unknown";
        }
        
        return $status;
    }
    
    public function customer()
    {
    	return $this->belongsTo('App\Customer');
    }

    public function warehouse()
    {
        return $this->belongsTo('App\Warehouse');
    }

    public function scopeGenerateNumber($query)
    {
        $unique = false;
        while ($unique == false) {
            $randomID = 'SO-'.now()->format('ym').'-'.rand(1000, 9999);
            $check = $query->where('so_number',$randomID)->count();
            if ($check > 0) {
              $unique = false;
            } else {
              $unique = true;
            }
        }
        return $randomID;    
    }

    public function scopeAvailable($query)
    {
        return $query->where('status', 100);
    }
}

app/Http/Controllers/SalesOrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use App\Inventory;
use App\SalesOrder;
use Session;
use DB;

class SalesOrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $sales_orders = SalesOrder::with('customer');
            $sales_orders = $sales_orders->select('*');
            
            return Datatables::of($sales_orders)
                ->addIndexColumn()
                ->addColumn('action', function($sales_order){
                    return view('partials._action', [
                        'model'           => $sales_order,
                        'form_url'        => route('sales-order.destroy', $sales_order->id),
                        'edit_url'        => route('sales-order.edit', $sales_order->id),
                        'show_url'        => route('sales-order.show', $sales_order->id)
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('sales-orders.index'); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $so_number = SalesOrder::generateNumber();

        return view('sales-orders.create')->with(compact('so_number'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
          'so_number' => 'required|string',
          'customer_id' => 'required|integer',
          'warehouse_id' => 'required|integer',
          'quantity' => 'required|integer',
          'volume' => 'required|integer',
          'delivery_date' => 'required|date',
          'description' => 'required|string',
        ]);

        DB::beginTransaction();
        
        $sales_order = new SalesOrder;
        $sales_order->so_number = $request->so_number;
        $sales_order->customer_id = $request->customer_id;
        $sales_order->warehouse_id = $request->warehouse_id;
        $sales_order->quantity = $request->quantity;
        $sales_order->volume = $request->volume;
        $sales_order->delivery_date = $request->delivery_date;
        $sales_order->description = $request->description;
        $sales_order->save();

        $inventory = Inventory::where('warehouse_id', $request->warehouse_id)->first();

        if ($inventory) {
            
            $left = $inventory->quantity - $request->quantity;

            if ($left < 0) {
                DB::rollback();

                Session::flash("flash_notification", [
                  "level"=>"warning",
                  "message"=>"Quantity inventory tidak mencukupi untuk order ini!"
                ]);
                return redirect()->back();
            }

            $inventory->quantity = $left;
            $inventory->save();

        } else {
            DB::rollback();

            Session::flash("flash_notification", [
              "level"=>"warning",
              "message"=>"Data Inventory belum tersedia, silahkan buat terlebih dahulu!"
            ]);
            return redirect()->back();
        }

        DB::commit();

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Sales Order dengan kode $sales_order->so_number berhasil dibuat"
        ]);
        
        return redirect()->route('sales-order.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $sales_order = SalesOrder::find($id);

        return view('sales-orders.show')->with(compact('sales_order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sales_order = SalesOrder::find($id);

        return view('sales-orders.edit')->with(compact('sales_order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
          'so_number' => 'required|string',
          'customer_id' => 'required|integer',
          'warehouse_id' => 'required|integer',
          'quantity' => 'required|integer',
          'volume' => 'required|integer',
          'delivery_date' => 'required|date',
          'description' => 'required|string',
        ]);
        
        DB::beginTransaction();

        $sales_order = SalesOrder::find($id);
        $sales_order->so_number = $request->so_number;
        $sales_order->customer_id = $request->customer_id;
        $sales_order->warehouse_id = $request->warehouse_id;
        
        $data['statement'] = 'unknown';
        $data['difference'] = 0;
        $changes = false;

        if ($sales_order->quantity != $request->quantity) {
            
            $changes = true;

            if ($sales_order->quantity < $request->quantity) {
                $data['statement'] = 'minus';
                $data['difference'] = $request->quantity - $sales_order->quantity;
            } else {
                $data['statement'] = 'plus';
                $data['difference'] = $sales_order->quantity - $request->quantity;
            }
        }

        $sales_order->quantity = $request->quantity;

        $sales_order->volume = $request->volume;
        $sales_order->delivery_date = $request->delivery_date;
        $sales_order->description = $request->description;
        
        if ($request->status != null) {
            $sales_order->status = $request->status;
        }

        $sales_order->save();

        if ($changes == true) {
            $inventory = Inventory::where('warehouse_id', $request->warehouse_id)->first();

            if ($inventory) {

                if ($data['statement'] == 'minus') {
                    $new_qty = $inventory->quantity - $data['difference'];

                    if ($new_qty < 0) {
                        DB::rollback();

                        Session::flash("flash_notification", [
                          "level"=>"warning",
                          "message"=>"Quantity inventory tidak mencukupi untuk order ini!"
                        ]);
                        return redirect()->back();
                    }
                } else {
                    $new_qty = $inventory->quantity + $data['difference'];
                }
                
                $inventory->quantity = $new_qty;
                $inventory->save();

            } else {
                DB::rollback();

                Session::flash("flash_notification", [
                  "level"=>"warning",
                  "message"=>"Data Inventory belum tersedia, silahkan buat terlebih dahulu!"
                ]);
                return redirect()->back();
            }
        }

        DB::commit();

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Sales Order dengan kode $sales_order->so_number berhasil diubah"
        ]);
        
        return redirect()->route('sales-order.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sales_order = SalesOrder::destroy($id);

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menghapus data"
        ]);

        return redirect()->route('sales-order.index');
    }
}

resources/views/sales-orders/create.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Sales Order</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Tambah Sales Order</h6>
        </div>
        <div class="card-body">
          
          <form method="POST" action="{{ route('sales-order.store') }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="form-group {{ $errors->has('so_number') ? ' has-error' : '' }}">
              <label for="so_number">SO Number</label>
              <input id="so_number" type="text" class="form-control @if ($errors->has('so_number')) is-invalid @endif" name="so_number" tabindex="1" value="{{ $so_number }}" readonly="tr">
              @if ($errors->has('so_number'))
                <div class="invalid-feedback">
                  {{ $errors->first('so_number') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('customer_id') ? ' has-error' : '' }}">
              <label for="customer_id">Customer</label>
              <select id="customer_id" class="form-control @if ($errors->has('customer_id')) is-invalid @endif" name="customer_id" tabindex="1">
                <option value=""></option>
                @foreach (\App\Customer::all() as $item)
                  <option value="{{ $item->id }}">{{ $item->name }}</option>
                @endforeach
              </select>
              @if ($errors->has('customer_id'))
                <div class="invalid-feedback">
                  {{ $errors->first('customer_id') }}
                </div>
              @endif
            </div>

            <div class="row">
              <div class="col-md-6">
                <div class="form-group {{ $errors->has('quantity') ? ' has-error' : '' }}">
                  <label for="quantity">Quantity</label>
                  <div class="input-group mb-2">
                    <input id="quantity" type="number" class="form-control @if ($errors->has('quantity')) is-invalid @endif" name="quantity" tabindex="1" value="{{ old('quantity') }}">
                    <div class="input-group-append">
                      <div class="input-group-text">unit</div>
                    </div>
                  </div>
                  @if ($errors->has('quantity'))
                    <div class="invalid-feedback">
                      {{ $errors->first('quantity') }}
                    </div>
                  @endif
                </div>
              </div>
              
              <div class="col-md-6">
                <div class="form-group {{ $errors->has('volume') ? ' has-error' : '' }}">
                  <label for="volume">Volume</label>              
                  <div class="input-group mb-2">
                    <input id="volume" type="number" class="form-control @if ($errors->has('volume')) is-invalid @endif" name="volume" tabindex="1" value="{{ old('volume') }}">
                    <div class="input-group-append">
                      <div class="input-group-text">cm<sup>3</sup></div>
                    </div>
                  </div>
                  @if ($errors->has('volume'))
                    <div class="invalid-feedback">
                      {{ $errors->first('volume') }}
                    </div>
                  @endif
                </div>
              </div>
            </div>

            <div class="form-group {{ $errors->has('warehouse_id') ? ' has-error' : '' }}">
              <label for="warehouse_id">Dari Warehouse</label>
              <select id="warehouse_id" class="form-control @if ($errors->has('warehouse_id')) is-invalid @endif" name="warehouse_id" tabindex="1">
                <option value=""></option>
                @foreach (\App\Warehouse::all() as $item)
                  <option value="{{ $item->id }}">{{ $item->name }}</option>
                @endforeach
              </select>
              @if ($errors->has('warehouse_id'))
                <div class="invalid-feedback">
                  {{ $errors->first('warehouse_id') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('delivery_date') ? ' has-error' : '' }}">
              <label for="delivery_date">Delivery Date</label>
              <input id="delivery_date" type="date" class="form-control @if ($errors->has('delivery_date')) is-invalid @endif" name="delivery_date" tabindex="1" value="{{ old('delivery_date') }}">
              @if ($errors->has('delivery_date'))
                <div class="invalid-feedback">
                  {{ $errors->first('delivery_date') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
              <label for="description">Keterangan</label>
              <input id="description" type="text" class="form-control @if ($errors->has('description')) is-invalid @endif" name="description" tabindex="1" value="{{ old('description') }}">
              @if ($errors->has('description'))
                <div class="invalid-feedback">
                  {{ $errors->first('description') }}
                </div>
              @endif
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" tabindex="1">
                Simpan
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
  <script type="text/javascript">
    $(document).ready(function() {
      $('#customer_id').select2({
        placeholder: "Pilih Customer"
      });

      $('#warehouse_id').select2({
        placeholder: "Pilih Warehouse"
      });
    });
  </script>
@endsection

resources/views/sales-orders/edit.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Sales Order</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Edit Sales Order</h6>
        </div>
        <div class="card-body">
          
          <form method="POST" action="{{ route('sales-order.update', $sales_order->id) }}" enctype="multipart/form-data">
            @csrf
            @method('PUT')

            <div class="form-group {{ $errors->has('so_number') ? ' has-error' : '' }}">
              <label for="so_number">SO Number</label>
              <input id="so_number" type="text" class="form-control @if ($errors->has('so_number')) is-invalid @endif" name="so_number" tabindex="1" value="{{ $sales_order->so_number }}" readonly="tr">
              @if ($errors->has('so_number'))
                <div class="invalid-feedback">
                  {{ $errors->first('so_number') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('customer_id') ? ' has-error' : '' }}">
              <label for="customer_id">Customer</label>
              <select id="customer_id" class="form-control @if ($errors->has('customer_id')) is-invalid @endif" name="customer_id" tabindex="1">
                <option value=""></option>
                @foreach (\App\Customer::all() as $item)
                  <option value="{{ $item->id }}" @if ($sales_order->customer_id == $item->id) selected @endif>{{ $item->name }}</option>
                @endforeach
              </select>
              @if ($errors->has('customer_id'))
                <div class="invalid-feedback">
                  {{ $errors->first('customer_id') }}
                </div>
              @endif
            </div>

            <div class="row">
              <div class="col-md-6">
                <div class="form-group {{ $errors->has('quantity') ? ' has-error' : '' }}">
                  <label for="quantity">Quantity</label>
                  <div class="input-group mb-2">
                    <input id="quantity" type="number" class="form-control @if ($errors->has('quantity')) is-invalid @endif" name="quantity" tabindex="1" value="{{ $sales_order->quantity }}">
                    <div class="input-group-append">
                      <div class="input-group-text">unit</div>
                    </div>
                  </div>
                  @if ($errors->has('quantity'))
                    <div class="invalid-feedback">
                      {{ $errors->first('quantity') }}
                    </div>
                  @endif
                </div>
              </div>
              
              <div class="col-md-6">
                <div class="form-group {{ $errors->has('volume') ? ' has-error' : '' }}">
                  <label for="volume">Volume</label>              
                  <div class="input-group mb-2">
                    <input id="volume" type="number" class="form-control @if ($errors->has('volume')) is-invalid @endif" name="volume" tabindex="1" value="{{ $sales_order->volume }}">
                    <div class="input-group-append">
                      <div class="input-group-text">cm<sup>3</sup></div>
                    </div>
                  </div>
                  @if ($errors->has('volume'))
                    <div class="invalid-feedback">
                      {{ $errors->first('volume') }}
                    </div>
                  @endif
                </div>
              </div>
            </div>

            <div class="form-group {{ $errors->has('warehouse_id') ? ' has-error' : '' }}">
              <label for="warehouse_id">Dari Warehouse</label>
              <select id="warehouse_id" class="form-control @if ($errors->has('warehouse_id')) is-invalid @endif" name="warehouse_id" tabindex="1">
                <option value=""></option>
                @foreach (\App\Warehouse::all() as $item)
                  <option value="{{ $item->id }}" @if ($sales_order->warehouse_id == $item->id) selected @endif>{{ $item->name }}</option>
                @endforeach
              </select>
              @if ($errors->has('warehouse_id'))
                <div class="invalid-feedback">
                  {{ $errors->first('warehouse_id') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('delivery_date') ? ' has-error' : '' }}">
              <label for="delivery_date">Delivery Date</label>
              <input id="delivery_date" type="date" class="form-control @if ($errors->has('delivery_date')) is-invalid @endif" name="delivery_date" tabindex="1" value="{{ $sales_order->delivery_date }}">
              @if ($errors->has('delivery_date'))
                <div class="invalid-feedback">
                  {{ $errors->first('delivery_date') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
              <label for="description">Keterangan</label>
              <input id="description" type="text" class="form-control @if ($errors->has('description')) is-invalid @endif" name="description" tabindex="1" value="{{ $sales_order->description }}">
              @if ($errors->has('description'))
                <div class="invalid-feedback">
                  {{ $errors->first('description') }}
                </div>
              @endif
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" tabindex="1">
                Simpan
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
  <script type="text/javascript">
    $(document).ready(function() {
      $('#customer_id').select2({
        placeholder: "Pilih Customer"
      });

      $('#warehouse_id').select2({
        placeholder: "Pilih Warehouse"
      });
    });
  </script>
@endsection

resources/views/sales-orders/index.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-start mb-4">
    <h1 class="h3 mb-0 text-gray-800">Sales Order</h1>
    <a class="btn btn-sm btn-primary mr-auto ml-4" href="{{ route('sales-order.create') }}"><i class="fa fa-plus"></i> Tambah Data</a> 
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">List Sales Order</h6>
        </div>
        <div class="card-body">

        <div class="table-responsive">
          <table class="table table-hover table-bordered datatable">
            <thead>                                 
              <tr>
                <th>#</th>
                <th>SO Number</th>
                <th>Customer</th>
                <th>Quantity</th>
                <th>Volume (cm<sup>3</sup>)</th>
                <th>Date</th>
                <th>Status</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>

        </div>
      </div>
    </div>
  </div>
@endsection
@section('script')
<script>
  $(document).ready(function() {
      $('.datatable').DataTable({
          processing: true,
          serverSide: true,
          autoWidth: false,
          language: {
              url: '{{ asset('vendor/sb-temp/vendor/datatables/lang/Indonesian.json') }}'
          },
          ajax: {
            url: '{{ route('sales-order.index') }}'
          },
          columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'so_number', name: 'so_number'},
            {data: 'customer.name', name: 'customer.name'},
            {data: 'quantity', name: 'quantity'},
            {data: 'volume', name: 'volume'},
            {data: 'delivery_date', name: 'delivery_date'},
            {data: 'display_status', name: 'display_status', orderable: false, searchable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      $(document).on('click','.js-submit-confirm', function(e){
          e.preventDefault();
          swal({
            title: 'Apakah anda yakin ingin menghapus?',
            text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              $(this).closest('form').submit();
            } 
          });
      });
  });
</script>
@endsection

resources/views/sales-orders/show.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Sales Order</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Detail Sales Order</h6>
        </div>
        <div class="card-body">
          
          <p>
            SO Number: <br><strong>{{$sales_order->so_number}}</strong>
            <hr>
          </p>
          <p>
            Customer: <br><strong>{{$sales_order->customer->name}}</strong>
            <hr>
          </p>
          <p>
            Alamat: <br><strong>{{$sales_order->customer->address}}</strong>
            <hr>
          </p>
          <p>
            Kecamatan: <br><strong>{{$sales_order->customer->district->name}}</strong>
            <hr>
          </p>
          <p>
            Kota / Kabupaten: <br><strong>{{$sales_order->customer->city->name}}</strong>
            <hr>
          </p>
          <p>
            Provisi: <br><strong>{{$sales_order->customer->province->name}}</strong>
            <hr>
          </p>
          <p>
            Quantity: <br><strong>{{$sales_order->quantity}} unit</strong>
            <hr>
          </p>
          <p>
            Volume: <br><strong>{{$sales_order->volume}} cm<sup>3</sup></strong>
            <hr>
          </p>
          <p>
            Delivery Date: <br><strong>{{$sales_order->delivery_date}}</strong>
            <hr>
          </p>
          <p>
            Keterangan: <br><strong>{{$sales_order->description}}</strong>
            <hr>
          </p>
          <p>
            Status: <br><strong>{{$sales_order->display_status}}</strong>
            <hr>
          </p>

        </div>
      </div>
    </div>
  </div>
@endsection